@hostname=47.96.254.64
@appname=myapp
@url=http://{{hostname}}/{{appname}}

### Login

POST {{url}}/login
Content-Type: application/x-www-form-urlencoded

username=lingshin&
password=lingshin

###

POST {{url}}/account/add
Content-Type: application/x-www-form-urlencoded
Cookie: JSESSIONID={{Login.response.cookies.JSESSIONID.value}}

name=陈睿&
username=cherry&
password=1234&
role=college_leader

###

POST {{url}}/student/add
Content-Type: application/x-www-form-urlencoded

student_id=301234123128&
name=lxy&
gender=男&
id_number=411524200407208022&
phone_number=19858172400

### lxy

POST {{url}}/student/update
Content-Type: application/x-www-form-urlencoded

student_id=301234123128&
name=lxy&
gender=男&
id_number=411524200407208022&
phone_number=19858172400&
nation=汉&
birth_date=2004-9-30&
birth_place=bzd&
country=中国&
home_address=西方极乐世界&
email=244151@qq.com&
dorm_id=219&
grade=1&
college=不知道&
major=计算机&
campus=校区&
entrance_date=2022-2-22&
class_id=10&
wechat=1985445&
qq=244151&
home_phone_number=451451451&
home_contact_man=佛祖&
mentor_id=1&
mentor=不知道

### delete

DELETE {{url}}/student/delete?id=6
Content-Type: application/x-www-form-urlencoded

###

POST {{url}}/account/password?id=4&password=Meteor@123
Cookie: JSESSIONID={{Login.response.cookies.JSESSIONID.value}}
Content-Type: application/x-www-form-urlencoded

###

GET  {{url}}/student/list
